name: build-fastapi

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/fahad-shaikh09/fastapi-test:latest .

      - name: Push image
        run: docker push ghcr.io/fahad-shaikh09/fastapi-test:latest